server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    #gateway网关配置
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      #路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能。
          predicates:
            - Path=/payment/selectById/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能。
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
            #- Cookie=username,yu   #例：curl http://localhost:9527/user/1 --cookie "username=yu"
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式 例：curl http://localhost:9527/user/1 -H "X-Request-Id:123"
            #- Host=**.macrozheng.com  #例：curl http://localhost:9527/user/1 -H "Host:www.macrozheng.com"
            #- Method=POST  #例：curl -X POST http://localhost:9527/user/1
            #- Query=username #带指定查询参数，例：curl http://localhost:9527/user/getByUsername?username=macro


#eureka配置
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka #单机版

